
com:
  technical:
    test:
      employees:
        employee1:
          id: 1
          status: 'UP'
          data:
            employeeName: 'Andres'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
        employee2:
          id: 2
          status: 'UP'
          data:
            employeeName: 'Carlos'
            employeeSalary: 10000
            employeeAge: 26
            profileImageUrl: 'urlTest'
        employee3:
          id: 3
          status: 'UP'
          data:
            employeeName: 'Juan'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
        employee4:
          id: 4
          status: 'DOWN'
          data:
            employeeName: 'Pedro'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
        employee5:
          id: 5
          status: 'UP'
          data:
            employeeName: 'Oscar'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
