
com:
  technical:
    test:
      employees:
        employee1:
          id: 1
<<<<<<< HEAD
          imageUrl: "https://hub.dummyapis.com/Image?text=OR&height=120&width=120"
          firstName: "TestFirst1"
          lastName: "TestLast1"
          email: "test1@example.com"
          contactNumber: "4342895816"
          age: 27
          dob: "03/04/1997"
          salary: 1.0
          address: "Address1"
        employee2:
          id: 2
          imageUrl: "https://hub.dummyapis.com/Image?text=LS&height=120&width=120"
          firstName: "TestFirst2"
          lastName: "TestLast2"
          email: "test2@example.com"
          contactNumber: "4910893400"
          age: 34
          dob: "30/06/1990"
          salary: 2.0
          address: "Address2"
        employee3:
          id: 3
          imageUrl: "https://hub.dummyapis.com/Image?text=NA&height=120&width=120"
          firstName: "TestFirst3"
          lastName: "TestLast3"
          email: "test3@example.com"
          contactNumber: "4591790646"
          age: 36
          dob: "23/04/1988"
          salary: 3.0
          address: "Address3"
        employee4:
          id: 4
          imageUrl: "https://hub.dummyapis.com/Image?text=JK&height=120&width=120"
          firstName: "TestFirst4"
          lastName: "TestLast4"
          email: "test4@example.com"
          contactNumber: "4651995827"
          age: 76
          dob: "31/07/1948"
          salary: 4.0
          address: "Address4"
        employee5:
          id: 5
          imageUrl: "https://hub.dummyapis.com/Image?text=JC&height=120&width=120"
          firstName: "TestFirst5"
          lastName: "TestLast5"
          email: "test5@example.com"
          contactNumber: "4447295483"
          age: 45
          dob: "17/04/1979"
          salary: 5.0
          address: "Address5"
        employee6:
          id: 6
          imageUrl: "https://hub.dummyapis.com/Image?text=NE&height=120&width=120"
          firstName: "TestFirst6"
          lastName: "TestLast6"
          email: "test6@example.com"
          contactNumber: "4719598777"
          age: 75
          dob: "14/06/1949"
          salary: 6.0
          address: "Address6"
        employee7:
          id: 7
          imageUrl: "https://hub.dummyapis.com/Image?text=JB&height=120&width=120"
          firstName: "TestFirst7"
          lastName: "TestLast7"
          email: "test7@example.com"
          contactNumber: "4886393149"
          age: 53
          dob: "19/01/1971"
          salary: 7.0
          address: "Address7"
        employee8:
          id: 8
          imageUrl: "https://hub.dummyapis.com/Image?text=AB&height=120&width=120"
          firstName: "TestFirst8"
          lastName: "TestLast8"
          email: "test8@example.com"
          contactNumber: "4199398705"
          age: 42
          dob: "15/08/1982"
          salary: 8.0
          address: "Address8"
        employee9:
          id: 9
          imageUrl: "https://hub.dummyapis.com/Image?text=AC&height=120&width=120"
          firstName: "TestFirst9"
          lastName: "TestLast9"
          email: "test9@example.com"
          contactNumber: "4608295589"
          age: 75
          dob: "21/10/1949"
          salary: 9.0
          address: "Address9"
        employee10:
          id: 10
          imageUrl: "https://hub.dummyapis.com/Image?text=SW&height=120&width=120"
          firstName: "TestFirst10"
          lastName: "TestLast10"
          email: "test10@example.com"
          contactNumber: "4796793395"
          age: 54
          dob: "02/03/1970"
          salary: 10.0
          address: "Address10"



=======
          status: 'UP'
          data:
            employeeName: 'Andres'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
        employee2:
          id: 2
          status: 'UP'
          data:
            employeeName: 'Carlos'
            employeeSalary: 10000
            employeeAge: 26
            profileImageUrl: 'urlTest'
        employee3:
          id: 3
          status: 'UP'
          data:
            employeeName: 'Juan'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
        employee4:
          id: 4
          status: 'DOWN'
          data:
            employeeName: 'Pedro'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
        employee5:
          id: 5
          status: 'UP'
          data:
            employeeName: 'Oscar'
            employeeSalary: 12000
            employeeAge: 24
            profileImageUrl: 'urlTest'
>>>>>>> cff0e96d62514e87f4fad1dd69bb871130958161
